jie65535/awesome-balatro

README.md
Added mods that I created which bypass the score cap and add new jokers and tarot cards.
=> Added my mods

README.md
Made the description slightly more specific. I'll keep updating the exact numbers as I update the mod!
=> Updated Mika's Mod Collection

README.md
Hope you like these mods! Feedback appreciated.
=> Added kjossul's mods

README.md
Bunco mod by me. Sorry if I messed up something with this PR!
=> Add Bunco mod

README-zh_CN.md, README.md
Fix Steamodded example_mods links that were broken by Steamopollys/Steamodded@eee6c483198d6905962ae14dc7422fb048270d4e
=> Fix Steamodded example_mods links

README.md
Looks like the line was copied and the link was never replaced
=> Fix FloundersJokers link

README.md
Add a new hotkeys collection with a wider range of features
=> Add hotkeys collection

README.md
=> Add JokerDisplay mod

README.md
(I don't know enough Chinese to fix the zh README.)
=> Add Nihility Challenge

README.md
I'd been searching for this exact mod for ages and could never find it, turns out the features were hidden away behind "improved"
=> Add a little bit more description to Cartomancer

README.md
Added my own mod to the list. Don't know if this is the right section since the mod doesn't need any modloader to function.
=> Add Balatro Ultimate Speedup Mod

README.md
Hey, I've made a deck and would like to add it to the collection!
=> Added Pauper Deck

README.md
Hi!~
I had to go out of my way to make sure this works with and without SteamModded bc we touch the same code, but put it in the Lovely category because it works just fine without (and is, I suppose, more likely to cause conflicts than something that sticks to SteamModded APIs).
I say this because I like blending in and would rather not be making a new heading, but I think Lovely > GUI is the right place >u<
=> Add Planet Card Cash-Out Mod

README-zh_CN.md, README.md
Apologies for the Chinese machine translation. Please improve if necessary.
=> Add SystemClock mod

README.md
Made this in a few hours. It makes the color pop well on the black background, and I also tried my shot at the jokers and other cards (collabs too).
=> Add EclipseTextures mod

README.md
Improves readability of the game, especially on lower res screens (Steam Deck) by using a more legible vector typeface, smoothly upscaled card textures and other small tweaks.
=> Add Readabletro mod

README.md
Adds my mod Fortlatro which adds a variety of Fortnite themed stuff i'd like more people to find it its pretty cool
=> Add Fortlatro

README.md
=> Add Jimbo's Metrics

README.md
I created a DNA Splice deck and tag that gives a free DNA Joker. It can also be configured if that joker is negative. Added it to the README
=> Add DNA splice deck and tag

README.md
I created a mod called BalaQuints which retextures some jokers and other cards into characters from The Quintessential Quintuplets. Added it to the README
=> Added BalaQuints

README.md
adds my own Panley Joker. Added to readme.
=> add Panley joker

README.md
Thanks for making this mod compilation, would love to be part of it!
=> Add Harambe's Chosen mod

README.md
=> Add Quilombo

README.md
I wrote a couple small QoL mods others might find useful :)
=> Add BrainstormRerollButton and RestartRunButton

README.md
Thanks for this list of cool mods and resources. I found this very helpful. Because of this, I made my own fun mod I made that adds 30 new Jokers.
=> Added Milatro mod

README.md
=> typist: fix broken links to username `janw4ld`

README.md
Added under Tools section, in alphabetical order:
Motely by @tacodiva, a CPU SIMD fast seed searcher for Balatro written in C#
Ouija by @optimuspi, an immolate-based OpenCL seed searcher app written in python, c and opencl
Balatro Seed Oracle by @optimuspi, a Motely-based seed searcher with a visual drag & drop style filter builder, powered by JSON configs, DUCKDB, and love!
`pifreak loves you!`
=> Add Balatro Seed Searcher engines/apps under Tools section: Motely, Ouija, BalatroSeedOracle
